### ISSUE TITLE
Examples that don't use zambeze

### ISSUE THREAD

**Issue by wigging** [ORNL/Zambeze#137]
Some of the example scripts don't actually use zambeze. This includes the `https_test.py`, `merge_counts.py`, `sftp_test.py`, and `wordcount.py` files in zambeze/examples. I suggest removing these examples as they don't use the zambeze package.

**Comment by wigging** [comment]
The `simple_ordered_wordcount.py` example uses the `wordcount.py` and `merge_counts.py` files. So maybe those scripts need to remain in the repository.

**Comment by wigging** [comment]
Oops, the files exist in the dev-cleanup branch, not in the main branch.

**Comment by tskluzac** [comment]
You're exactly right that those are used by the simple_ordered_wordcounts example. Basically the example is meant to represent 'separate' python scripts that can be transferred around and executed alongside the data themselves.

**Comment by tskluzac** [comment]
But you also point to an important point. We should probably document these tests to show what they are actually testing. Let me know if you have a recommendation/strategy for test documentation.

**Comment by wigging** [comment]
For the `simple_ordered_wordcount.py` example, you could put the files into a directory to make it more obvious that they are related to each other.

```
examples/
└── simple_ordered_wordcount/
    ├── run_ordered_wordcount.py
    ├── wordcount.py
    └── merge_counts.py
```

**Comment by tskluzac** [comment]
I like this idea re: organizing the examples. 

One additional question: 
-- I'm thinking if there's another SHELL command example we could run (in lieu of imagemagick) to demonstrate performing a computation from the shell. I'm thinking down the lines of something that can be done solely in a BASH script without additional params. We could grep files for words, return an ls of the working directory, or something of that sort. Any thoughts? My creative juices aren't all that creative at the moment...

**Comment by wigging** [comment]
You could have a bash script that creates a text file, iterates over a range of numbers, and for each number writes a line of text to the text file.

**Comment by wigging** [comment]
Example of a bash script that writes ten lines to a text file:

```bash
echo "Running example..."

for i in {1..10}; do
    echo "This is line $i" >> myexample.txt;
done

echo "Done."
```

**Comment by tskluzac** [comment]
Closed from https://github.com/ORNL/Zambeze/pull/143
