### ISSUE TITLE
The zambeze.org just points to this repository

### ISSUE THREAD

**Issue by wigging** [ORNL/Zambeze#142]
The zambeze.org link in the About section on the GitHub repository page just redirects to this repository. It looks like zambeze.org is being used as the domain name for the documentation. So why not link to the documentation in the About section? There's no need to link back the repository.

**Comment by tskluzac** [comment]
I think linking to the About section is a great idea -- is there anything that needs to be done from the domain, or can this all be accomplished in the Zambeze repo itself?

**Comment by wigging** [comment]
Just to clarify, my suggestion is to get rid of the `zambeze.org` and replace it with `docs.zambeze.org` which points to the Sphinx documentation that is generated/hosted with Read The Docs. Otherwise, zambeze.org by itself doesn't actually point to anything. Is there supposed be a website at zambeze.org that you want people to see?

<img width="328" alt="Screenshot 2024-03-13 at 11 24 35 AM" src="https://github.com/ORNL/Zambeze/assets/6828967/e369d3fc-98f7-4c6c-afb3-6a5b86903001">

**Comment by wigging** [comment]
Changed the url to docs.zambeze.org.
