### ISSUE TITLE
Missing some modules that are needed for tests

### ISSUE THREAD

**Issue by wigging** [ORNL/Zambeze#147]
There are missing modules in zambeze that are needed for the tests.

In test_activity_shell.py the following module is missing:
- `zambeze.orchestration.identity`

In test_campaign.py, test_globus_uri_separator.py, test_plugin_globus.py, and test_plugin_globus_common.py the following module is missing:
- `zambeze.orchestration.plugin_modules.globus`

The missing modules are causing tests to fail.

**Comment by tskluzac** [comment]
It looks like identity was kicked to utils: https://github.com/ORNL/Zambeze/tree/main/zambeze/utils 

And I don't believe that we are using the Globus plugin anymore -- we've swapped to use the transfer hippo instead (so that test will need to be rewritten).

**Comment by wigging** [comment]
I'm also having issues with building the docs due to missing modules.

**Comment by wigging** [comment]
This has been fixed in recent pull requests.
