### ISSUE TITLE
Simplify CLI to not use typer in an external bin directory

### ISSUE THREAD

**Issue by tskluzac** [ORNL/Zambeze#160]
Currently, we would like to simplify the CLI code structure to remove the typer dependency for the project. We can also remove the CLI files from the external /bin/ directory to ensure that they are safely embedded in the project. Ideally we could have a single cli.py file at the top level of the package, and this would be our entrypoint in pyproject.toml. 

@wigging recommended going back to a simple argparse+entrypoint model given the simplicity of our CLI. I agree with it.

**Comment by wigging** [comment]
Part of this has been addressed by merge request #162 which removed the bin directory and moved CLI into the package source directory.
