### ISSUE TITLE
"globus://" file URI support 

### ISSUE THREAD

**Issue by tskluzac** [ORNL/Zambeze#38]
We want to create a multi-site Globus data fabric for all machines running Zambeze agents: 

- [x] Change file model to support "globus://" URIs 
- [x] Examine file URIs -- if "globus://" is present, start Globus Auth login
- [x] Enable "auth once, run many times" model where user context (i.e., tokens) are hidden
- [x] Investigate how tokens are handled if expiration in middle of transfer (and document)
- [x] Move all browser-based auth to Campaign() level

**Comment by JoshuaSBrown** [comment]
I think this has already been partially, done I'll have to find the exact Globus PR that switched to using the globus:// URIs.

**Comment by tskluzac** [comment]
Completed. Will close upon merge of dev-clean to main.
