### ISSUE TITLE
Queue Abstraction Layer - RabbitMQ, NATS support

### ISSUE THREAD

**Issue by JoshuaSBrown** [ORNL/zambeze#59]
The Queue abstraction layer is implemented, but what is needed is the RabbitMQ client to make this work.

**Comment by JoshuaSBrown** [comment]
@tskluzac, I had already added this but I think this is what you mentioned in the DevOps meeting.

**Comment by JoshuaSBrown** [comment]
This is being addressed in Tyler's PR.

**Comment by tskluzac** [comment]
RabbitMQ abstraction added in https://github.com/ORNL/zambeze/pull/101

NATS support to be removed.
