### ISSUE TITLE
Fix bug preventing zambeze agent from working

### ISSUE THREAD

**Issue by JoshuaSBrown** [ORNL/zambeze#63]

**Comment by rafaelfsilva** [comment]
@JoshuaSBrown, could you provide a short description of the bug? Thanks!

**Comment by JoshuaSBrown** [comment]
Good point,

The main loop of the agent was throwing an exception because the NATS nextMsg command was throwing a timeout. This is not an actual error, so the fix was to catch the Timeout and allow the loop to continue.

**Comment by JoshuaSBrown** [comment]
Will close automatically when devel is merged into main.
