### ISSUE TITLE
OpenAPI Schema - implement into Message Object

### ISSUE THREAD

**Issue by JoshuaSBrown** [ORNL/Zambeze#66]
The currently being developed version of the message body and interface does not use OpenAPI, but it would preferable and simpler to use the OpenAPI schema python libraries to implement that part.

Here is the initial issue:
https://github.com/ORNL/zambeze/issues/52

**Comment by rafaelfsilva** [comment]
@JoshuaSBrown, I thought OpenAPI schema was mostly for RESTful services. Could you please elaborate more what would be the intended use here? Thanks!

**Comment by JoshuaSBrown** [comment]
> @JoshuaSBrown, I thought OpenAPI schema was mostly for RESTful services. Could you please elaborate more what would be the intended use here? Thanks!

It is not so much the RESTful services that would be useful but the scheme library functionality. If you look at what I have implemented in Zambeze for validating user inputs, there are much better tools that are more capable of doing this with decent documentation. I do not yet know which technology would be the most ideal I just know they exist and would probably improve the readability.

**Comment by tskluzac** [comment]
Closing without completion as we'll be adhering to INTERSECT message structure.
