### ISSUE TITLE
user science campaign

### ISSUE THREAD

**Issue by ketancmaheshwari** [ORNL/zambeze#7]
A science user who likes to get some computation done via Zambeze. How do they proceed and what are the step-by-step instructions for them?

The campaign definition is as follows:

Input data: 10 time series images: {01-10}.jpg.
Process: An ImageMagick convert command: convert -delay 20 -loop 0 *.jpg a.gif
Expected output: An animated gif file called a.gif

**Comment by rafaelfsilva** [comment]
hi @ketancmaheshwari, I will keep evolving the high-level campaign definition for this use case. For now, we have:
```
from zambeze import Activity, Campaign, ShellAction

campaign = Campaign("My ImageMagick Campaign")

activity = Activity("ImageMagick", files=[f"file:///{i:02d}.jpg" for i in range(1, 11)])
action = ShellAction(
    "ImageMagick",
    command="convert",
    params=["-delay", "20", "-loop", "0", "*.jpg", "a.gif"],
)

campaign.add_activity(activity)
campaign.run()
```
