### ISSUE TITLE
Thread Safety Processor & Agent

### ISSUE THREAD

**Issue by JoshuaSBrown** [ORNL/Zambeze#76]
Currently, zambeze is using two threads, which I will call the main thread and the processor thread. The main thread runs the agent the processor thread \is launched by the agent and then executes an asynchronous event loop. The main thread listens for a zmq message and whenever one is received it will launch a temporary asynchronous event loop to send the message to the queue. Currently, there are no constructs in the agent or processor classes to prevent memory corruption should either thread access objects that they share.

This whole design either needs to be changed/redesigned or thread locking needs to be implemented.

**Comment by JoshuaSBrown** [comment]
This is being addressed via python queues in Tylers PR.

**Comment by rafaelfsilva** [comment]
@JoshuaSBrown, please review the code and close if everything looks good

**Comment by tskluzac** [comment]
Closing due to https://stackoverflow.com/questions/14053102/is-python-queue-queue-get-and-put-thread-safe
